CREATE TABLE MAIL_DEDUP (
	ACCOUNT_ID TEXT NOT NULL,
	MESSAGE_ID TEXT NOT NULL,
	CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX UX_MAIL_DEDUP ON MAIL_DEDUP(ACCOUNT_ID, MESSAGE_ID);